sonar.projectKey=gitcombo_vulnerable-node
sonar.organization=gitcombo
sonar.projectName=vulnerable-node

sonar.sources=model,routes,src
sonar.tests=tests
sonar.sourceEncoding=UTF-8
sonar.javascript.file.suffixes=.js

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=\
  node_modules/**,\
  coverage/**,\
  public/**,\
  views/**,\
  services/**,\
  docs/**,\
  logs/**,\
  dist/**,\
  **/*.min.js,\
  **/*.test.js,\
  **/*.spec.js,\
  dummy.js,\
  bin/**

sonar.coverage.exclusions=\
  tests/**,\
  dummy.js,\
  config.js,\
  bin/**,\
  model/init_db.js,\
  model/db.js

sonar.cpd.exclusions=\
  tests/**,\
  public/**
